backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  squash_merges: true
site_url: https://axelradclimbing.com
display_url: https://axelradclimbing.com
logo_url: https://axelradclimbing.com/images/icon.png
publish_mode: editorial_workflow # enable drafts
show_preview_links: true # show post / page live preview
media_folder: 'src/images' # Media files will be stored in the repo
collections:
  # Blog posts
  - name: 'posts' # Used in routes, e.g., /admin/collections/blog
    identifier_field: name
    description: 'A collection of all blog posts'
    label: 'Posts' # Used in the UI
    label_singular: 'Post' # Used in the UI
    folder: 'src/posts' # The path to the folder where the documents are stored
    path: '{{year}}-{{month}}-{{day}}-{{slug}}/index'
    create: true # Allow users to create new documents in this collection
    preview_path: 'posts/{{year}}-{{month}}-{{day}}-{{title}}/index.html' # preview location
    media_folder: 'uploads'
    public_folder: 'uploads'
    preview_path_date_field: 'date'
    summary: '{{fields.title}} - {{fields.date}}'
    sort: 'date:desc'
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          default: Created,
          format: "YYYY-MM-DD",
          date_format: "LL", # e.g. 24.12.2021
          time_format: false,
        }
      - {
          label: 'Update Date',
          name: 'update',
          widget: 'datetime',
          default: Last Modified,
          format: "YYYY-MM-DD",
          date_format: "LL", # e.g. 24.12.2021
          time_format: false,
          required: false
        }
      # - { label: 'Draft', name: 'draft', widget: 'boolean', default: True }
      - { label: 'Author', name: 'author', widget: 'select', options: ["Itai Axelrad", "Eden Axelrad"]}
      - { label: 'Location', name: 'location', widget: 'string', required: false}
      - { label: 'Feature Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list'}
      - { label: 'Body', name: 'body', widget: 'markdown' }

  # Pages
  - name: 'pages' # Used in routes, e.g., /admin/collections/blog
    identifier_field: name
    description: 'A collection of all blog pages'
    label: 'Pages' # Used in the UI
    label_singular: 'Page' # Used in the UI
    files:
      - label: 'About Page'
        name: 'about'
        file: 'src/pages/about.njk'
        fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Body', name: 'body', widget: 'markdown' }

  # Logbook
  - name: 'logbook' # Used in routes, e.g., /admin/collections/blog
    identifier_field: name
    description: 'A collection of boulders'
    label: 'Logbook' # Used in the UI
    files:
      - label: 'Boulders'
        name: 'boulders'
        file: 'src/data/boulders.json'
        fields:
          - label: Boulders
            name: boulders
            widget: list
            allow_add: true
            fields: # The fields for each document, usually in front matter
              - {
                  label: 'Type',
                  name: 'type',
                  widget: 'string',
                  default: 'Boulder',
                }
              - { label: 'Route', name: 'route', widget: 'string' }
              - { label: 'Crag', name: 'crag', widget: 'string' }
              - { label: 'Sector', name: 'sector', widget: 'string' }
              - {
                  label: 'Grade',
                  name: 'grade',
                  widget: 'string',
                  pattern:
                    [
                      '\d[a-zA-Z]?\+?',
                      'Must have number at start , optionally followed by letter and plus',
                    ],
                }
              - {
                  label: 'Date',
                  name: 'date',
                  widget: 'datetime',
                  default: Created,
                }
              - { label: 'Comment', name: 'comment', widget: 'string' }
              - { label: 'Quality', name: 'quality', widget: 'string' }
              - { label: 'Style', name: 'style', widget: 'string' }
              - { label: 'Country', name: 'country', widget: 'string' }
              - { label: 'Region', name: 'region', widget: 'string' }
              - { label: 'Tag', name: 'tag', widget: 'string' }
